
name: CI

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out site
        uses: actions/checkout@v2
        with:
          submodules: true 
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      - name: Build site
        run: hugo --minify
      - name: Deploy to Azure
        uses: tibor19/static-website-deploy@v1
        with:
          enabled-static-website: 'true'
          folder: 'public'
          connection-string: ${{ secrets.CONNECTION_STRING }}
      - name: Purge cache
        uses: jakejarvis/cloudflare-purge-action@v0.3.0
        env: 
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}

